name: CI
on: push
jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: luacheck
        uses: lunarmodules/luacheck@v1

  tests:
    strategy:
      matrix:
        lua-version: ["5.1.5", "5.2.4", "5.3.6", "5.4.4"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: localua
        run: |
          curl https://loadk.com/localua.sh -O
          chmod +x localua.sh
          ./localua.sh .lua "${{ matrix.lua-version }}"

      - name: run tests
        run: |
          ./.lua/bin/luarocks test
